<a href="https://colab.research.google.com/github/koll-ai/control-meme-api/blob/main/Controlmeme_Colab_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Install deps & run webui in separate process ( ~2 min)

In [1]:
!curl -Lo memfix.zip https://github.com/nolanaatama/sd-webui/raw/main/memfix.zip
!unzip /content/memfix.zip
!apt install -qq libunwind8-dev
!dpkg -i *.deb
%env LD_PRELOAD=libtcmalloc.so
!rm *
!pip install --upgrade fastapi==0.90.1
!git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui
!git clone https://github.com/nolanaatama/sd-webui-tunnels /content/stable-diffusion-webui/extensions/sd-webui-tunnels
!git clone https://github.com/Mikubill/sd-webui-controlnet /content/stable-diffusion-webui/extensions/sd-webui-controlnet
!git clone https://github.com/fkunn1326/openpose-editor /content/stable-diffusion-webui/extensions/openpose-editor
!git clone https://github.com/yfszzx/stable-diffusion-webui-images-browser /content/stable-diffusion-webui/extensions/stable-diffusion-webui-images-browser
!git clone https://github.com/DominikDoom/a1111-sd-webui-tagcomplete /content/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete
# Model Code
!curl -Lo /content/stable-diffusion-webui/models/Stable-diffusion/dreamshaper3.32bvcf.ckpt https://huggingface.co/Lykon/DreamShaper/resolve/main/Dreamshaper_3.32_baked_vae_clip_fix.ckpt
# ControlNet
!curl -Lo /content/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_canny.safetensors https://huggingface.co/webui/ControlNet-modules-safetensors/resolve/main/control_canny-fp16.safetensors
!curl -Lo /content/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_depth.safetensors https://huggingface.co/webui/ControlNet-modules-safetensors/resolve/main/control_depth-fp16.safetensors
!curl -Lo /content/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_hed-fp16.safetensors https://huggingface.co/webui/ControlNet-modules-safetensors/resolve/main/control_hed-fp16.safetensors
!curl -Lo /content/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_mlsd-fp16.safetensors https://huggingface.co/webui/ControlNet-modules-safetensors/resolve/main/control_mlsd-fp16.safetensors
!curl -Lo /content/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_normal-fp16.safetensors https://huggingface.co/webui/ControlNet-modules-safetensors/resolve/main/control_normal-fp16.safetensors
!curl -Lo /content/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_openpose-fp16.safetensors https://huggingface.co/webui/ControlNet-modules-safetensors/resolve/main/control_openpose-fp16.safetensors
!curl -Lo /content/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_scribble-fp16.safetensors https://huggingface.co/webui/ControlNet-modules-safetensors/resolve/main/control_scribble-fp16.safetensors
!curl -Lo /content/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_seg-fp16.safetensors https://huggingface.co/webui/ControlNet-modules-safetensors/resolve/main/control_seg-fp16.safetensors
import shutil
shutil.rmtree('/content/stable-diffusion-webui/embeddings')
%cd /content/stable-diffusion-webui
!git checkout 0cc0ee1
!git clone https://huggingface.co/nolanaatama/embeddings
# Web UI tunnel (use cloudflare by default)
# If cloudflare failed to start, we may try these options:
# Change '--cloudflared' to '--remotemoe' on the COMMANDLINE_ARGS line above to use remotemoe tunnel
# Change '--cloudflared' to '--localhostrun' to use localhost.run tunnel
# Change '--cloudflared' to '--share' to use gradio tunnel
!curl -Lo /content/stable-diffusion-webui/models/Lora/wanostyle_2.safetensors https://huggingface.co/nolanaatama/opwslora/resolve/main/onePieceWanoStyle_20.safetensors
!curl -Lo /content/stable-diffusion-webui/models/Lora/last.pt https://huggingface.co/closertodeath/dpepmkmp/resolve/main/last.pt
!curl -Lo /content/stable-diffusion-webui/models/Lora/anime_screencap_v2-000030.safetensors https://huggingface.co/nolanaatama/asslora/resolve/main/asslora.safetensors

!npm i -g localtunnel
!pip install flask
!pip install flask_cors


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  761k  100  761k    0     0  13.5M      0 --:--:-- --:--:-- --:--:-- 13.5M
Archive:  /content/memfix.zip
  inflating: google-perftools_2.5-2.2ubuntu3_all.deb  
  inflating: libtcmalloc-minimal4_2.5-2.2ubuntu3_amd64.deb  
  inflating: libgoogle-perftools4_2.5-2.2ubuntu3_amd64.deb  
  inflating: libgoogle-perftools-dev_2.5-2.2ubuntu3_amd64.deb  
The following NEW packages will be installed:
  libunwind-dev
0 upgraded, 1 newly installed, 0 to remove and 22 not upgraded.
Need to get 472 kB of archives.
After this operation, 4,163 kB of additional disk space will be used.
Selecting previously unselected package libunwind-dev:amd64.
(Reading database ... 128215 files and directories currently installed.)
Preparing to unpack .../libunwind-dev_1.2.1-9build1

# Now restart the kernel (execution > restart kernel) and execute the following


In [2]:

import torch
import cv2
import numpy as np
from PIL import Image

from flask import Flask
from flask import request, send_file
import base64
from io import BytesIO
import os

import subprocess
import time
from flask_cors import CORS

import requests


from io import BytesIO
import sys
sys.path.append('/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts')
sys.path.append('/content/stable-diffusion-webui/extensions/sd-webui-controlnet')
import cv2
from processor import canny, simple_scribble, hed, unload_hed, fake_scribble, mlsd, unload_mlsd, midas, midas_normal, unload_midas, leres, unload_leres, openpose, openpose_hand, unload_openpose, uniformer, unload_uniformer, pidinet, unload_pidinet
import imutils
from PIL import Image
import os
import subprocess
import time

from base64 import b64encode

In [19]:
import cv2 as cv

def cv_to_b64(cv_image):
    _, im_arr = cv2.imencode('.jpg', cv_image)  # im_arr: image in Numpy one-dim array format.
    im_bytes = im_arr.tobytes()
    im_b64 = base64.b64encode(im_bytes)
    return im_b64

def adjust_size(width, height):
    ratio = width/height
    if(ratio > 1):
        width = 512
        round_width = width

        height = round(512 * 1/ratio)
        round_height = ((height + 32) // 64) * 64
        round_height = int(max(round_height, 64))
    else:
        height = 512
        round_height = height

        width = round(512 * ratio) 
        round_width = ((width + 32) // 64) * 64
        round_width = int(max(round_width, 64))

    return round_width, round_height

class controlnetRequest():
    def __init__(self, hint, **kwargs ):
        self.url = "http://localhost:7860/controlnet/txt2img"

        w, h = adjust_size(hint.shape[1], hint.shape[0])

        #resized = cv2.resize(hint, (w, h))
        hint_b64 = cv_to_b64(hint)
        hint_b64 = hint_b64.decode("utf-8")

        # get the parameters from the kwargs or use default value
        self.body = {
            "prompt": kwargs.get("prompt", ""),
            "negative_prompt": kwargs.get("negative_prompt", ""),
            "seed": kwargs.get("seed", -1),
            "subseed": kwargs.get("subseed", -1),
            "subseed_strength": kwargs.get("subseed_strength", 0),
            "batch_size": kwargs.get("batch_size", 1),
            "n_iter": kwargs.get("n_iter", 1),
            "steps": kwargs.get("steps", 30),
            "cfg_scale": kwargs.get("cfg_scale", 7),
            "width": w,
            "height": h,
            "restore_faces": kwargs.get("restore_faces", True),
            "eta": kwargs.get("eta", 0),
            "sampler_index": kwargs.get("sampler_index", "Euler a"),
            "controlnet_input_image": [hint_b64],
            "controlnet_module": kwargs.get("controlnet_module", "none"),
            "controlnet_model": kwargs.get("controlnet_model", "control_canny [e3fe7712]"),
            "controlnet_guidance": kwargs.get("controlnet_guidance", 1.0)
        }
            

    def sendRequest(self):
        r = requests.post(self.url, json=self.body)
        return r.json()


def create_hint(init_image, processor_model, controlnet_processor_res=512, thresholdA=None, thresholdB=None):
    """ Create a hint image from the initial image and the processor model
    Args:
        init_image: np array of the initial image 
        processor_model: the processor model, one of the following: 
            - canny
            - simple_scribble
            - hed
            - fake_scribble
            - mlsd
            - midas
            - midas_normal
            - leres
            - openpose
            - openpose_hand
            - uniformer
        thresholdA: the threshold A
        thresholdB: the threshold B
    """
    if processor_model == "canny":
        return canny(init_image, controlnet_processor_res, thresholdA, thresholdB)
    elif processor_model == "hed":
        return hed(init_image, controlnet_processor_res)
    elif processor_model == "mlsd":
        return mlsd(init_image, controlnet_processor_res, thresholdA, thresholdB)
    elif processor_model == "depth":
        return midas(init_image, controlnet_processor_res, np.pi * 2.0)
    elif processor_model == "normal_map":
        return midas_normal(init_image, controlnet_processor_res, np.pi * 2.0, thresholdA)
    elif processor_model == "depth_leres":
        return leres(init_image, controlnet_processor_res, np.pi * 2.0, thresholdA, thresholdB)
    elif processor_model == "openpose":
        return openpose(init_image, controlnet_processor_res, False)
    elif processor_model == "openpose_hand":
        return openpose_hand(init_image, controlnet_processor_res, True)
    elif processor_model == "fake_scribble":
        return fake_scribble(init_image, controlnet_processor_res)
    elif processor_model == "segmentation":
        return uniformer(init_image, controlnet_processor_res)
    elif processor_model == "pidinet":
        return pidinet(init_image, controlnet_processor_res)
    else:
        return None
    
    

def generate_controlnet(hint, **kwargs):
    """ Generate the controlnet meme by making a request to local api
    Args:
        hint: the hint image b64 encoded
        kwargs: the parameters of the controlnet
            - nb_steps: the number of steps
            - prompt: the prompt
            - guess_mode: false if we want to use the prompt, true if we want to use the guess
    Returns:
        List of images generated by controlnet
    """
    
    req = controlnetRequest(hint, **kwargs)
    resp = req.sendRequest()
    print(resp)
    
    return resp['images']
    

In [10]:
%%file /content/make_video.sh
# https://gist.github.com/anguyen8/d0630b6aef6c1cd79b9a1341e88a573e


#!/bin/bash

# Anh Nguyen <anh.ng8@gmail.com>
# 2016-04-30
# MIT License

# This script takes in same-size images from a folder and make a crossfade video from the images using ffmpeg.
# Make sure you have ffmpeg installed before running.

# The output command looks something like the below, but for as many images as you have in the folder.
# See the answer by LordNeckbeard at:
# http://superuser.com/questions/833232/create-video-with-5-images-with-fadein-out-effect-in-ffmpeg/1071748#1071748
#
#
# ffmpeg \
# -loop 1 -t 1 -i 001.png \
# -loop 1 -t 1 -i 002.png \
# -loop 1 -t 1 -i 003.png \
# -loop 1 -t 1 -i 004.png \
# -loop 1 -t 1 -i 005.png \
# -filter_complex \
# "[1:v][0:v]blend=all_expr='A*(if(gte(T,0.5),1,T/0.5))+B*(1-(if(gte(T,0.5),1,T/0.5)))'[b1v]; \
# [2:v][1:v]blend=all_expr='A*(if(gte(T,0.5),1,T/0.5))+B*(1-(if(gte(T,0.5),1,T/0.5)))'[b2v]; \
# [3:v][2:v]blend=all_expr='A*(if(gte(T,0.5),1,T/0.5))+B*(1-(if(gte(T,0.5),1,T/0.5)))'[b3v]; \
# [4:v][3:v]blend=all_expr='A*(if(gte(T,0.5),1,T/0.5))+B*(1-(if(gte(T,0.5),1,T/0.5)))'[b4v]; \
# [0:v][b1v][1:v][b2v][2:v][b3v][3:v][b4v][4:v]concat=n=9:v=1:a=0,format=yuv420p[v]" -map "[v]" out.mp4

#----------------------------------------------------------------
# SETTINGS
input_dir="/content/video"  # Replace this by a path to your folder /path/to/your/folder
n_files=3                        # Replace this by a number of images
files=`ls ${input_dir}/*.jpeg | head -${n_files}`  # Change the file type to the correct type of your images
output_file="/content/video.mp4"           # Name of output video
crossfade=0.9                     # Crossfade duration between two images
#----------------------------------------------------------------

# Making an ffmpeg script...
input=""
filters=""
output="[0:v]"

i=0

for f in ${files}; do
  input+=" -loop 1 -t 1 -i $f"

  next=$((i+1))
  if [ "${i}" -ne "$((n_files-1))" ]; then
    filters+=" [${next}:v][${i}:v]blend=all_expr='A*(if(gte(T,${crossfade}),1,T/${crossfade}))+B*(1-(if(gte(T,${crossfade}),1,T/${crossfade})))'[b${next}v];"
  fi

  if [ "${i}" -gt "0" ]; then
    output+="[b${i}v][${i}:v]"
  fi

  i=$((i+1))
done

output+="concat=n=$((i * 2 - 1)):v=1:a=0,format=yuv420p[v]\" -map \"[v]\" ${output_file}"

script="ffmpeg ${input} -filter_complex \"${filters} ${output}"

echo ${script}

# Run it
eval "${script}"

Overwriting /content/make_video.sh


In [6]:
def generate_video_ffmep(img1_url, img2_url):
  !mkdir -p /content/video

  !wget -O /content/video/im1.jpeg {img1_url}
  !wget -O /content/video/im2.jpeg {img2_url}
  !cp /content/video/im1.jpeg /content/video/im3.jpeg
  !yes | bash /content/make_video.sh

  return '/content/video.mp4'



# Finaly, run this cell and click on the outputed meme.koll.ai?gpuURL=XXX to be redirected to the website or copy https://XXX in the colabsessionlink textfield. 
#Wait for sd-webui API to be started before making generation, logs are in /content/output_webui.txt ( ~3 min)
(ready when 127.0.0.1 url and cloudfare url are displayed at the end of the file)

In [20]:
%cd /content/stable-diffusion-webui

# run localtunnel
with open('/content/output_tunnel.txt', 'w') as f:
    proc = subprocess.Popen(['lt', '--port', '5000'], stdout=f)



os.environ['COMMANDLINE_ARGS'] = "--api --allow-code	--enable-insecure-extension-access	--disable-safe-unpickle --no-half-vae --xformers --reinstall-xformers --enable-insecure-extension- --gradio-queue --cloudflared" 
os.environ['REQS_FILE'] = "requirements.txt"
# del os.environ['REQS_FILE']

with open('/content/output_webui.txt', 'w') as f:
    proc_automatic = subprocess.Popen(['python', '-u', 'launch.py'], stdout=f, stderr=f)


time.sleep(3)

app = Flask(__name__)
CORS(app)

params = dict()

API_URL  = ""
BACK_URL = "https://controle-meme-back-n7bkntouja-uc.a.run.app"


#Route to generate the hint according to processor, thresholdA and thresholdB
@app.route('/hint/', methods=['POST'])
def hint():
    params = request.get_json()
    meme_url = params['controlnet_basememe_url']
    processor_model = params['controlnet_module']
    thresholdA = params['controlnet_threshold_a']
    thresholdB = params['controlnet_threshold_b']
    
    # read the image from the url to cv2
    base_meme = imutils.url_to_image(meme_url)    
    hint = create_hint(base_meme, processor_model, thresholdA=thresholdA, thresholdB = thresholdB)
    hint = hint[0]
    # hint = Image.fromarray(hint)
    print(type(hint))
    print(hint)
    
    # # convert the hint to bytes
    # buffered = BytesIO()
    # hint.save(buffered, format="JPEG")
    
    # # encode the bytes to base64
    # img_str = base64.b64encode(buffered.getvalue())

    im_b64 = cv_to_b64(hint)
    
    return im_b64


@app.route('/', methods=['POST'])
def index():
    global params

    params = request.get_json()
    meme_url = params['controlnet_basememe_url']
    processor_module = params['controlnet_module']
    thresholdA = params['controlnet_threshold_a']
    thresholdB = params['controlnet_threshold_b']
        
    # read the image from the url to cv2
    base_meme = imutils.url_to_image(meme_url)    
    hint = create_hint(base_meme, processor_module, thresholdA=thresholdA, thresholdB = thresholdB)
    hint = hint[0]

    # todo: send request to sdwebui api to get the generated image
    try: 
        last_image = generate_controlnet(hint, **params)
    except requests.exceptions.ConnectionError:
        return "Automatic api subprocess is not fully started yet, please try again in a minute", 500
      
    last_image_b64 = last_image[0]
    
    # with open('./last_meme.jpeg', 'w') as f:
    #   Image.open(BytesIO(base64.b64decode(last_image))).save(f, format="JPEG")
    print('START')
    print(last_image_b64)
    print(type(last_image_b64))
    print('END')
    # with open("./last_meme.jpeg", "wb") as f:
    #    f.write(last_image_b64)


    decoded_data = base64.b64decode(last_image_b64)
    np_data = np.fromstring(decoded_data,np.uint8)
    img = cv2.imdecode(np_data,cv2.IMREAD_UNCHANGED)

    cv2.imwrite('./last_meme.jpeg', img)



    return last_image_b64



@app.route('/save_last/')
def save_last():
    global params

    # last_image = Image.open('./last_meme.jpeg')
    # buffered = BytesIO()
    # last_image.save(buffered, format="JPEG")
    # img_str = base64.b64encode(buffered.getvalue())

    last_image = cv2.imread('./last_meme.jpeg')
    img_str = cv_to_b64(last_image)

    data = dict(
        memeID = params['uuid'],
        imageb64=img_str.decode("utf-8"),
        prompt=params.get('prompt', 'no prompt'),
        nb_steps=params.get('nb_steps', 'no data'),
        parent_url = params.get('parent_url')
    )
    url = f'{BACK_URL}/api/save_variation/'
    print('url', url)
    requests.post(url, json = data)

    return "ok"


@app.route('/generate_video/', methods=['POST'])
def generate_video():
    params = request.get_json()
    
    parent_url = params['parent_url']
    variation_url = params['variation_url']

    path_video = generate_video_ffmep(parent_url, variation_url)

    return send_file(path_video)




@app.route('/hello/')
def hello():    
    return "hello"

# todo: add route to check if automatic api is started


if __name__ == '__main__':
  with open('/content/output_tunnel.txt', 'r') as f:
      contents = f.read()
      API_URL = contents.split(' ')[-1]
      protocol = API_URL.split(':')[0]
      url = API_URL.split('/')[-1]

      print(API_URL)

      print('\n'*2)
      print(f'Everything is ready! Click on the this link to be redirected to koll.ai. Don\'t close this tab!')
      print(f'>>>>  https://meme.koll.ai?gpuURL={url}  <<<<')

  app.run()

/content/stable-diffusion-webui
https://young-pumas-juggle-34-126-153-77.loca.lt




Everything is ready! Click on the this link to be redirected to koll.ai. Don't close this tab!
>>>>  https://meme.koll.ai?gpuURL=young-pumas-juggle-34-126-153-77.loca.lt
  <<<<
 * Serving Flask app '__main__'
 * Debug mode: off


INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:36:26] "OPTIONS / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:36:27] "POST / HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:36:46] "OPTIONS / HTTP/1.1" 200 -
<ipython-input-20-9e1f2a831077>:91: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np_data = np.fromstring(decoded_data,np.uint8)
INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:37:25] "POST / HTTP/1.1" 200 -


{'images': ['iVBORw0KGgoAAAANSUhEUgAAAgAAAAFACAIAAABFqlNcAAACBHRFWHRwYXJhbWV0ZXJzAExpbmsgZnJvbSBMZWdlbmQgb2YgWmVsZGEgbG9va2luZyBiYWNrIGF0IGdhbm9uZG9yZi4gNGssIHRyZW5kaW5nIG9uIGFydHN0YXRpb24sIGNlbGwgc2hhZGluZywgbWFzdGVycGllY2UKU3RlcHM6IDMwLCBTYW1wbGVyOiBFdWxlciBhLCBDRkcgc2NhbGU6IDcuMCwgU2VlZDogMjg4NTc3NDA1NiwgRmFjZSByZXN0b3JhdGlvbjogQ29kZUZvcm1lciwgU2l6ZTogNTEyeDMyMCwgTW9kZWwgaGFzaDogYmQxOTYwMmNlMCwgTW9kZWw6IGRyZWFtc2hhcGVyMy4zMmJ2Y2YsIFNlZWQgcmVzaXplIGZyb206IC0xeC0xLCBEZW5vaXNpbmcgc3RyZW5ndGg6IDAsIENvbnRyb2xOZXQgRW5hYmxlZDogVHJ1ZSwgQ29udHJvbE5ldCBNb2R1bGU6IGNhbm55LCBDb250cm9sTmV0IE1vZGVsOiBjb250cm9sX2Nhbm55IFtlM2ZlNzcxMl0sIENvbnRyb2xOZXQgV2VpZ2h0OiAxLjAsIENvbnRyb2xOZXQgR3VpZGFuY2UgU3RhcnQ6IDAuMCwgQ29udHJvbE5ldCBHdWlkYW5jZSBFbmQ6IDEuMCwgRXRhOiAwLjBlQcX+AAEAAElEQVR4nJT9WcwtWXYeiH1r7b0j4kz/dOchp6qsqqxisQaWOIlqkhpIdUuWbbVhtBuw4Ue3Hwy/2A+G0bD7pV+6DdhPBvxgw2601ZBguSFLUNMlURTVlChSYpE1ZlYOlZk3b97pn/8zRcTea/lhDxHnv1kl+eTJ/54TJ8Y9fGutbw2bvvlXf0vhFQoCiEEgAAARAYh/QOkDDR8BSl9B8WPeO2+Mp6DhQ9k7n5KA3e3

INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:37:38] "OPTIONS /save_last/ HTTP/1.1" 200 -


url https://controle-meme-back-n7bkntouja-uc.a.run.app/api/save_variation/


INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:37:46] "GET /save_last/ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:37:47] "OPTIONS / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:37:54] "POST / HTTP/1.1" 200 -


{'images': ['iVBORw0KGgoAAAANSUhEUgAAAgAAAAFACAIAAABFqlNcAAACA3RFWHRwYXJhbWV0ZXJzAExpbmsgZnJvbSBMZWdlbmQgb2YgWmVsZGEgbG9va2luZyBiYWNrIGF0IGdhbm9uZG9yZi4gNGssIHRyZW5kaW5nIG9uIGFydHN0YXRpb24sIGNlbGwgc2hhZGluZywgbWFzdGVycGllY2UKU3RlcHM6IDMwLCBTYW1wbGVyOiBFdWxlciBhLCBDRkcgc2NhbGU6IDcuMCwgU2VlZDogMzg3MjU2NjcyLCBGYWNlIHJlc3RvcmF0aW9uOiBDb2RlRm9ybWVyLCBTaXplOiA1MTJ4MzIwLCBNb2RlbCBoYXNoOiBiZDE5NjAyY2UwLCBNb2RlbDogZHJlYW1zaGFwZXIzLjMyYnZjZiwgU2VlZCByZXNpemUgZnJvbTogLTF4LTEsIERlbm9pc2luZyBzdHJlbmd0aDogMCwgQ29udHJvbE5ldCBFbmFibGVkOiBUcnVlLCBDb250cm9sTmV0IE1vZHVsZTogY2FubnksIENvbnRyb2xOZXQgTW9kZWw6IGNvbnRyb2xfY2FubnkgW2UzZmU3NzEyXSwgQ29udHJvbE5ldCBXZWlnaHQ6IDEuMCwgQ29udHJvbE5ldCBHdWlkYW5jZSBTdGFydDogMC4wLCBDb250cm9sTmV0IEd1aWRhbmNlIEVuZDogMS4wLCBFdGE6IDAuMDV4sI4AAQAASURBVHiczP15tCbHdR8I/u6NyOXb3lr7hkKhgMJOECAIEOAq7hRJbdZqLe62x25P2z0jt8/Y53hm7Onu6Z4Ze9wedctu27IlmdRiURZFLRQpkuIikQRJECD2tQqFQu1Vb/3WXCLu/JEZkZHfe6Akn7E1eYBXX2ZGRkbEvfd3l7gRSceOvGc2NmRESAEMAogAAUEAgAQA1f/XBwX/0NzFHQX8v+6sqpaIqisCAs0/IdW

INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:38:21] "OPTIONS /save_last/ HTTP/1.1" 200 -


url https://controle-meme-back-n7bkntouja-uc.a.run.app/api/save_variation/


INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:38:23] "GET /save_last/ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:40:51] "OPTIONS / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:41:00] "POST / HTTP/1.1" 200 -


{'images': ['iVBORw0KGgoAAAANSUhEUgAAAgAAAAFACAIAAABFqlNcAAACA3RFWHRwYXJhbWV0ZXJzAExpbmsgZnJvbSBMZWdlbmQgb2YgWmVsZGEgbG9va2luZyBiYWNrIGF0IGdhbm9uZG9yZi4gNGssIHRyZW5kaW5nIG9uIGFydHN0YXRpb24sIGNlbGwgc2hhZGluZywgbWFzdGVycGllY2UKU3RlcHM6IDMwLCBTYW1wbGVyOiBFdWxlciBhLCBDRkcgc2NhbGU6IDcuMCwgU2VlZDogMzQ5NDEyNTkwLCBGYWNlIHJlc3RvcmF0aW9uOiBDb2RlRm9ybWVyLCBTaXplOiA1MTJ4MzIwLCBNb2RlbCBoYXNoOiBiZDE5NjAyY2UwLCBNb2RlbDogZHJlYW1zaGFwZXIzLjMyYnZjZiwgU2VlZCByZXNpemUgZnJvbTogLTF4LTEsIERlbm9pc2luZyBzdHJlbmd0aDogMCwgQ29udHJvbE5ldCBFbmFibGVkOiBUcnVlLCBDb250cm9sTmV0IE1vZHVsZTogY2FubnksIENvbnRyb2xOZXQgTW9kZWw6IGNvbnRyb2xfY2FubnkgW2UzZmU3NzEyXSwgQ29udHJvbE5ldCBXZWlnaHQ6IDEuMCwgQ29udHJvbE5ldCBHdWlkYW5jZSBTdGFydDogMC4wLCBDb250cm9sTmV0IEd1aWRhbmNlIEVuZDogMS4wLCBFdGE6IDAuMF2TqD0AAQAASURBVHiclP131G3JlR+G/fauOufc9OXv5djhvc7daOQwAAZhMDMYgpQ4MyJFiqRES6NkybItLVnSWvLykmTZsmgv2UuigimbkkiF4SRqiBkOBjMABkAjNDqh43uvu1/OX/5uOOdU7e0/zqk6db/XQ9sXD1/fe0KdCrt++7dD1SFwBqkRP0xQgMJPIiS/AEI4EM7o3Pn2AgBE4bBSV1z80156oPju9vYBD3xPSyDM/Zf

INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:45:17] "OPTIONS /hint/ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:45:17] "POST /hint/ HTTP/1.1" 200 -


<class 'numpy.ndarray'>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:46:00] "OPTIONS /hint/ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:46:01] "POST /hint/ HTTP/1.1" 200 -


<class 'numpy.ndarray'>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:46:11] "OPTIONS /hint/ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:46:12] "POST /hint/ HTTP/1.1" 200 -


<class 'numpy.ndarray'>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:46:18] "OPTIONS /hint/ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:46:18] "POST /hint/ HTTP/1.1" 200 -


<class 'numpy.ndarray'>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:47:37] "OPTIONS /hint/ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:47:38] "POST /hint/ HTTP/1.1" 200 -


<class 'numpy.ndarray'>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:47:50] "OPTIONS /hint/ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:47:51] "POST /hint/ HTTP/1.1" 200 -


<class 'numpy.ndarray'>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:47:55] "POST /hint/ HTTP/1.1" 200 -


<class 'numpy.ndarray'>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:47:58] "OPTIONS /hint/ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:47:58] "POST /hint/ HTTP/1.1" 200 -


<class 'numpy.ndarray'>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:48:16] "OPTIONS /hint/ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:48:17] "POST /hint/ HTTP/1.1" 200 -


<class 'numpy.ndarray'>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:48:25] "OPTIONS /hint/ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:48:26] "POST /hint/ HTTP/1.1" 200 -


<class 'numpy.ndarray'>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:48:31] "OPTIONS / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Mar/2023 21:48:38] "POST / HTTP/1.1" 200 -


{'images': ['iVBORw0KGgoAAAANSUhEUgAAAgAAAAFACAIAAABFqlNcAAABmHRFWHRwYXJhbWV0ZXJzAFN0ZXBzOiAzMCwgU2FtcGxlcjogRXVsZXIgYSwgQ0ZHIHNjYWxlOiA3LjAsIFNlZWQ6IDMyODMwNDMxNiwgRmFjZSByZXN0b3JhdGlvbjogQ29kZUZvcm1lciwgU2l6ZTogNTEyeDMyMCwgTW9kZWwgaGFzaDogYmQxOTYwMmNlMCwgTW9kZWw6IGRyZWFtc2hhcGVyMy4zMmJ2Y2YsIFNlZWQgcmVzaXplIGZyb206IC0xeC0xLCBEZW5vaXNpbmcgc3RyZW5ndGg6IDAsIENvbnRyb2xOZXQgRW5hYmxlZDogVHJ1ZSwgQ29udHJvbE5ldCBNb2R1bGU6IGNhbm55LCBDb250cm9sTmV0IE1vZGVsOiBjb250cm9sX2Nhbm55IFtlM2ZlNzcxMl0sIENvbnRyb2xOZXQgV2VpZ2h0OiAxLjAsIENvbnRyb2xOZXQgR3VpZGFuY2UgU3RhcnQ6IDAuMCwgQ29udHJvbE5ldCBHdWlkYW5jZSBFbmQ6IDEuMCwgRXRhOiAwLjCtOWmqAAEAAElEQVR4nLT9WY9lS5Ymhq3BzPZ0BneP6ca9N8eauqtJghJFiN0NkAAhECDABwF6EKAfIULSiwDpX+hBD5QESWgRbDYkUoJKFLvJakpq9ljVVVlZmZ3TzZt3iDnC3c+wJzNba+nB9jnhEfdmMruZtcPhcc6ezvZjZmv41rfWwj/78x8iGjEhGAAAIRggLJsZAEI5srxHMAMzA0QwO+9UNQQABFM7nW5QzoTyu7wAg9MeOx0wU7Ny3+UOy341PV8Op7NOO5frUFXLY5SLVJdPVQMzLdeVo+Xq8hQI5cLl1kioolgeGsvfjGo6ZPn058/+8d/+z3/6/e9d72+13BHe2b76FuFfcMM7v8977PTz3pn0lT145wHOP4BggIi

# Tests (ignore)

In [ ]:
meme_url = "https://storage.googleapis.com/control-meme-public/gigachad.jpg"

image = Image.open(requests.get(meme_url, stream=True).raw)
image

#get controlnet hint image
hint = create_hint(image, 'canny')
hint

params = {"prompt": "Gigachad Thanos",
          "hint": hint,
          "num_inference_steps": 30,
          "seed": -1
        }

b64 = generate_controlnet(**params)
b64

In [ ]:

meme_url = "https://storage.googleapis.com/control-meme-public/Salt-Bae-001.jpg"
processor_module = "canny"
thresholdA = 40
thresholdB = 120

# read the image from the url to cv2
base_meme = imutils.url_to_image(meme_url)    
hint = create_hint(base_meme, processor_module, thresholdA=thresholdA, thresholdB = thresholdB)
hint = Image.fromarray(hint)

# convert the hint to bytes
buffered = BytesIO()
hint.save(buffered, format="JPEG")

# encode the bytes to base64
hint_b64 = base64.b64encode(buffered.getvalue()).decode("utf-8")

# todo: send request to sdwebui api to get the generated image
last_image = generate_controlnet(hint_b64, **params)
last_image = last_image[0]

{'images': ['iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAABn3RFWHRwYXJhbWV0ZXJzAHNocmVrClN0ZXBzOiAzMCwgU2FtcGxlcjogRXVsZXIgYSwgQ0ZHIHNjYWxlOiA3LjAsIFNlZWQ6IDMzMTE3NjE0NDQsIEZhY2UgcmVzdG9yYXRpb246IENvZGVGb3JtZXIsIFNpemU6IDUxMng1MTIsIE1vZGVsIGhhc2g6IGJkMTk2MDJjZTAsIE1vZGVsOiBkcmVhbXNoYXBlcjMuMzJidmNmLCBTZWVkIHJlc2l6ZSBmcm9tOiAtMXgtMSwgRGVub2lzaW5nIHN0cmVuZ3RoOiAwLCBDb250cm9sTmV0IEVuYWJsZWQ6IFRydWUsIENvbnRyb2xOZXQgTW9kdWxlOiBjYW5ueSwgQ29udHJvbE5ldCBNb2RlbDogY29udHJvbF9jYW5ueSBbZTNmZTc3MTJdLCBDb250cm9sTmV0IFdlaWdodDogMS4wLCBDb250cm9sTmV0IEd1aWRhbmNlIFN0YXJ0OiAwLjAsIENvbnRyb2xOZXQgR3VpZGFuY2UgRW5kOiAxLjAsIEV0YTogMC4wZVX+EgABAABJREFUeJzc/XmsfVl2HoZ9a6299znnTm9+v7nGruqZTTUHtUiTomRNtmAZjqKMdpwgMCJAieEgCRwoMWAECfKXESBwIseDbAuODdiyREmJRNG0RVFqimNzEHuqrq6uql/Vb3rzHc/Ze6+18sd51WzKgiLDJAVx//Peffece++57+y91v7W932L/tgf/kNpErppl6sCiF1Ta805a1XAmyaY0W5XQuTJdLJebmop84OFZi2lLPZmtWq/2aY2htj0fZ7t7283q5KrVZXIklqGxSbdXC6vrq/m+/vr1a5r2zTtXlzdfPbTn3/x9pe/+dUvPX/+AkQhiNWhaVsSKtWJOSV9482H52cfPjpZbOv6M59M9w7k/Sc